Fix missing parenthesis around default invocation
Fixes:
```
Error: template: authelia/templates/secret.yaml:37:86: executing "authelia/templates/secret.yaml" at <default>: wrong number of args for default: want at least 1 got 0
```
Caused by recent changes here:
https://github.com/authelia/chartrepo/commit/17e7b94bb3b11fe0e7ab1b04d37af04cd2959724#diff-9189c2f5c1b19f1988198e0c692eea37875a6bc90ce03513fbcfa995a3238b91L34